config/routes.rb
Pharmavacancy::Application.routes.draw do

  get "job_alert" => "job_alert#index"
  post "job_alert" => "job_alert#create"
  get "ajax/keywords"
  get "ajax/locations"
  get "ajax/candidates"

  get "job/:id/apply_to_job" => "job_handler#apply_to_job"
  get "job/:id/apply_job" => "job_handler#apply_job"
  get "job/:id/save_job" => "job_handler#save_job"
  get "download_resume" => "common#download_resume"

  resources :candidates, :only => [:show, :edit, :update] do 
    match '/profile' => 'candidates#profile'
    match '/profile/edit/:profile_name' => 'candidates#profile_edit'
    post '/candidate_update/:profile_name' => 'candidates#update_profile'
    delete '/candidate_destroy/:profile_name/:profile_id' => 'candidates#destroy_profile'
    get "/application_history" => "application_history#index"
    get "/application_history/show/:job_id" => "application_history#show"
    get "/saved_jobs" => "application_history#saved_jobs"
    get "/change_password" => "candidates#change_password"
    get "/job_alert" => "candidates#job_alert"
  end

  get 'candidate_registration/new' => 'candidate_registration#new'
  get 'candidate_registration/:id/step2' => 'candidate_registration#registration_step2'
  get 'candidate_registration/:id/step3' => 'candidate_registration#registration_step3'
  post 'candidate_session/perform_login' => 'candidate_login#perform_login'
  post 'candidate_registration/step1' => 'candidate_registration#create'
  put 'candidate_registration/:id/step2' => 'candidate_registration#step2_update'
  put 'candidate_registration/:id/step3' => 'candidate_registration#step3_update'

  get 'employer/login' => 'employer_dashboard#login'
  get 'employer/reset_password' => 'employer_dashboard#reset_password'
  post 'perform_login' => 'session#perform_login'
  get 'employer_dashboard' => 'employer_dashboard#index'
  get 'employer/:id/change_password' => 'employer_dashboard#change_password'
  get 'employer/:id/jobs' => 'employer_dashboard#change_password'
  get 'session/logout' => 'session#logout'
  post 'session/change_password' => 'session#change_password'
  get 'dashboard' => 'dashboard#index'
  get 'get_location_cities/:id' => 'common#location_cities'
  get 'session/forgot_password' => 'session#forgot_password'
  post 'session/send_password' => 'session#send_password'
  get 'activate/:code' => 'session#activate_user'

  resources :employers do 
    get "/applied_candidates" => "employer_dashboard#applied_candidates"
    get "/candidate_profile/:id" => "employer_dashboard#candidate_profile"
    get "/candidates" => "employer_dashboard#candidates"
    get "/candidate_search" => "employer_dashboard#candidate_search"
    post "/perform_search" => "employer_dashboard#perform_search"
    get "/upgrade_plans" => "employer_dashboard#upgrade_plans"
    get "/place_order/:plan_id" => "employer_dashboard#place_order"
    post "/create_order" => "employer_dashboard#create_order"
    get "/confirm_order/:order_id" => "employer_dashboard#confirm_order"
    resources :jobs
  end

  namespace :admin do
    resources :users
    resources :industries
    resources :employers, :only => [:index, :destroy]
    resources :jobs, :only => [:index, :destroy]
    get 'pending_jobs' => "jobs#pending_jobs"
    post "approve_job/:id" => "jobs#approve_job"
    get '/' => 'login#index'
    get 'login' => 'login#index'
    post 'perform_login' => 'login#perform_login'
    get 'logout' => 'login#logout'
    get 'dashboard' => 'dashboard#index'
    get 'reset_password' => 'login#reset_password'
    resources :cities
    resources :locations
    resources :job_types
    resources :pg_qualifications
    resources :ug_qualifications
    resources :designations
    resources :vacancy_categories
    resources :plans
    resources :candidates, :only => [:index, :destroy]
    post "set_featured_employer/:id" => "employers#set_featured_employer"
    post "suspend_user/:id" => "users#suspend_user"
    post "change_plan/:id/:plan_id" => "employers#change_plan"
  end

  get '/job_by/:section' => "dashboard#job_by_section"
  get '/job_by/:filter/:filter_id' => "dashboard#job_by_filter"
  post 'search' => "dashboard#search"
  get '/advanced_search' => "dashboard#advanced_search"
  post '/advanced_search' => "dashboard#perform_advanced_search"

  root :to => 'dashboard#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
	
  #attr_accessor :name, :short_name

  validates :name, :presence => true
  has_many :cities
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_filter :verify_admin
  before_filter :set_admin_location, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /admin/locations
  # GET /admin/locations.json
  def index
    @admin_locations = Location.all
  end

  # GET /admin/locations/1
  # GET /admin/locations/1.json
  def show
  end

  # GET /admin/locations/new
  def new
    @admin_location = Location.new
  end

  # GET /admin/locations/1/edit
  def edit
  end

  # POST /admin/locations
  # POST /admin/locations.json
  def create
    @admin_location = Location.new(admin_location_params)

    respond_to do |format|
      if @admin_location.save
        format.html { redirect_to admin_locations_url, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @admin_location }
      else
        format.html { render :new }
        format.json { render json: @admin_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/locations/1
  # PATCH/PUT /admin/locations/1.json
  def update
    respond_to do |format|
      if @admin_location.update_attributes(admin_location_params)
        format.html { redirect_to admin_locations_url, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_location }
      else
        format.html { render :edit }
        format.json { render json: @admin_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/locations/1
  # DELETE /admin/locations/1.json
  def destroy
    @admin_location.destroy
    respond_to do |format|
      format.html { redirect_to admin_locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_location
      @admin_location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_location_params
      params.require(:location).permit(:name, :short_name)
    end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/views/admin/locations/_form.html.erb
<%= form_for(@admin_location, url: generate_admin_path(@admin_location)) do |f| %>
  <% if @admin_location.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @admin_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Enter name" %>
  </div>
  <div class="form-group">
    <%= f.label :short_name %>
    <%= f.text_field :short_name, :class => "form-control", :placeholder => "Enter short name" %>
  </div>  
  <button type="submit" class="btn btn-primary">Submit</button>
  &nbsp;
  <a href="<%= admin_locations_url %>"><button type="button" class="btn btn-primary">Cancel</button></a>
<% end %>

app/views/admin/locations/edit.html.erb
<h1>Editing Location</h1>
<br>
<%= render 'form' %>

app/views/admin/locations/index.html.erb
<div class="panel panel-default locations_grid_container">
  <%= render :partial => "/shared/success_message", :locals => { :message => notice } %>
  <!-- Default panel contents -->
  <div class="panel-heading">
    <div class="panel_heading_text">
      <h3>Locations</h3>
    </div>
    <div class="new_link_div">
      <a href="<%= new_admin_location_path %>" class="">
          <div class="btn-group btn-group-xs" role="group" aria-label="Extra-small button group">
            <button type="button" class="btn btn-warning">New Location</button>
          </div>
      </a>
    </div>
  </div>
  <!-- Table -->
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Short name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @admin_locations.each_with_index do |admin_location, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= admin_location.name %></td>
          <td><%= admin_location.short_name %></td>
          <td><%= link_to 'Edit', "#{edit_admin_location_path(admin_location)}" %> &nbsp;<%= link_to 'Destroy', "#{admin_location_path(admin_location)}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/locations/new.html.erb
<h1>New Location</h1>
<br>
<%= render 'form' %>

app/views/admin/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_location.name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @admin_location.short_name %>
</p>

<%= link_to 'Edit', edit_admin_location_path(@admin_location) %> |
<%= link_to 'Back', admin_locations_path %>