config/routes.rb
Pharmavacancy::Application.routes.draw do

  get "job_alert" => "job_alert#index"
  post "job_alert" => "job_alert#create"
  get "ajax/keywords"
  get "ajax/locations"
  get "ajax/candidates"

  get "job/:id/apply_to_job" => "job_handler#apply_to_job"
  get "job/:id/apply_job" => "job_handler#apply_job"
  get "job/:id/save_job" => "job_handler#save_job"
  get "download_resume" => "common#download_resume"

  resources :candidates, :only => [:show, :edit, :update] do 
    match '/profile' => 'candidates#profile'
    match '/profile/edit/:profile_name' => 'candidates#profile_edit'
    post '/candidate_update/:profile_name' => 'candidates#update_profile'
    delete '/candidate_destroy/:profile_name/:profile_id' => 'candidates#destroy_profile'
    get "/application_history" => "application_history#index"
    get "/application_history/show/:job_id" => "application_history#show"
    get "/saved_jobs" => "application_history#saved_jobs"
    get "/change_password" => "candidates#change_password"
    get "/job_alert" => "candidates#job_alert"
  end

  get 'candidate_registration/new' => 'candidate_registration#new'
  get 'candidate_registration/:id/step2' => 'candidate_registration#registration_step2'
  get 'candidate_registration/:id/step3' => 'candidate_registration#registration_step3'
  post 'candidate_session/perform_login' => 'candidate_login#perform_login'
  post 'candidate_registration/step1' => 'candidate_registration#create'
  put 'candidate_registration/:id/step2' => 'candidate_registration#step2_update'
  put 'candidate_registration/:id/step3' => 'candidate_registration#step3_update'

  get 'employer/login' => 'employer_dashboard#login'
  get 'employer/reset_password' => 'employer_dashboard#reset_password'
  post 'perform_login' => 'session#perform_login'
  get 'employer_dashboard' => 'employer_dashboard#index'
  get 'employer/:id/change_password' => 'employer_dashboard#change_password'
  get 'employer/:id/jobs' => 'employer_dashboard#change_password'
  get 'session/logout' => 'session#logout'
  post 'session/change_password' => 'session#change_password'
  get 'dashboard' => 'dashboard#index'
  get 'get_location_cities/:id' => 'common#location_cities'
  get 'session/forgot_password' => 'session#forgot_password'
  post 'session/send_password' => 'session#send_password'
  get 'activate/:code' => 'session#activate_user'

  resources :employers do 
    get "/applied_candidates" => "employer_dashboard#applied_candidates"
    get "/candidate_profile/:id" => "employer_dashboard#candidate_profile"
    get "/candidates" => "employer_dashboard#candidates"
    get "/candidate_search" => "employer_dashboard#candidate_search"
    post "/perform_search" => "employer_dashboard#perform_search"
    get "/upgrade_plans" => "employer_dashboard#upgrade_plans"
    get "/place_order/:plan_id" => "employer_dashboard#place_order"
    post "/create_order" => "employer_dashboard#create_order"
    get "/confirm_order/:order_id" => "employer_dashboard#confirm_order"
    resources :jobs
  end

  namespace :admin do
    resources :users
    resources :industries
    resources :employers, :only => [:index, :destroy]
    resources :jobs, :only => [:index, :destroy]
    get 'pending_jobs' => "jobs#pending_jobs"
    post "approve_job/:id" => "jobs#approve_job"
    get '/' => 'login#index'
    get 'login' => 'login#index'
    post 'perform_login' => 'login#perform_login'
    get 'logout' => 'login#logout'
    get 'dashboard' => 'dashboard#index'
    get 'reset_password' => 'login#reset_password'
    resources :cities
    resources :locations
    resources :job_types
    resources :pg_qualifications
    resources :ug_qualifications
    resources :designations
    resources :vacancy_categories
    resources :plans
    resources :candidates, :only => [:index, :destroy]
    post "set_featured_employer/:id" => "employers#set_featured_employer"
    post "suspend_user/:id" => "users#suspend_user"
    post "change_plan/:id/:plan_id" => "employers#change_plan"
  end

  get '/job_by/:section' => "dashboard#job_by_section"
  get '/job_by/:filter/:filter_id' => "dashboard#job_by_filter"
  post 'search' => "dashboard#search"
  get '/advanced_search' => "dashboard#advanced_search"
  post '/advanced_search' => "dashboard#perform_advanced_search"

  root :to => 'dashboard#index'

end

app/models/designation.rb
class Designation < ActiveRecord::Base
  #attr_accessor :name, :short_name
  belongs_to :vacancy_category
  validates :name, :presence => true
  validates :short_name, :presence => true
  validates :vacancy_category_id, :presence => true

  has_many :jobs, :foreign_key => :role_id
end

app/controllers/admin/designations_controller.rb
class Admin::DesignationsController < ApplicationController
  before_filter :verify_admin
  before_filter :set_admin_designation, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /admin/designations
  # GET /admin/designations.json
  def index
    @admin_designations = Designation.all
  end

  # GET /admin/designations/1
  # GET /admin/designations/1.json
  def show
  end

  # GET /admin/designations/new
  def new
    @admin_designation = Designation.new
  end

  # GET /admin/designations/1/edit
  def edit
  end

  # POST /admin/designations
  # POST /admin/designations.json
  def create
    @admin_designation = Designation.new(admin_designation_params)

    respond_to do |format|
      if @admin_designation.save
        format.html { redirect_to admin_designations_url, notice: 'Designation was successfully created.' }
        format.json { render :show, status: :created, location: @admin_designation }
      else
        format.html { render :new }
        format.json { render json: @admin_designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/designations/1
  # PATCH/PUT /admin/designations/1.json
  def update
    respond_to do |format|
      if @admin_designation.update_attributes(admin_designation_params)
        format.html { redirect_to admin_designations_url, notice: 'Designation was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @admin_designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/designations/1
  # DELETE /admin/designations/1.json
  def destroy
    @admin_designation.destroy
    respond_to do |format|
      format.html { redirect_to admin_designations_url, notice: 'Designation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_designation
      @admin_designation = Designation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_designation_params
      params.require(:designation).permit(:name, :short_name, :vacancy_category_id)
    end
end

app/helpers/admin/designations_helper.rb
module Admin::DesignationsHelper
end

app/views/admin/designations/_form.html.erb
<%= form_for(@admin_designation, url: generate_admin_path(@admin_designation)) do |f| %>
  <% if @admin_designation.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @admin_designation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Enter name" %>
  </div>
  <div class="form-group">
    <%= f.label :short_name %>
    <%= f.text_field :short_name, :class => "form-control", :placeholder => "Enter Short name" %>
  </div>
  <div class="form-group">
    <%= f.label :vacancy_category_id %>
    <%= f.collection_select :vacancy_category_id, VacancyCategory.all, :id, :name, {}, {:class => "form-control"}%>
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
  &nbsp;
  <a href="<%= admin_designations_url %>"><button type="button" class="btn btn-primary">Cancel</button></a>
<% end %>

app/views/admin/designations/edit.html.erb
<h1>Editing Admin Designation</h1>
<br>
<%= render 'form' %>

app/views/admin/designations/index.html.erb
<div class="panel panel-default designations_grid_container">
  <%= render :partial => "/shared/success_message", :locals => { :message => notice } %>
  <!-- Default panel contents -->
  <div class="panel-heading">
    <div class="panel_heading_text">
      <h3>Designations</h3>
    </div>
    <div class="new_link_div">
      <a href="<%= new_admin_designation_path %>" class="">
          <div class="btn-group btn-group-xs" role="group" aria-label="Extra-small button group">
            <button type="button" class="btn btn-warning">New Designation</button>
          </div>
      </a>
    </div>
  </div>
  <!-- Table -->
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Short name</th>
        <th>Vacancy category</th>
      </tr>
    </thead>
    <tbody>
      <% @admin_designations.each_with_index do |admin_designation, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= admin_designation.name %></td>
          <td><%= admin_designation.short_name %></td>
          <td>
            <%= admin_designation.vacancy_category.name if admin_designation.vacancy_category.present? %>
          </td>
          <td><%= link_to 'Edit', "#{edit_admin_designation_path(admin_designation.id)}" %> &nbsp;<%= link_to 'Destroy', "#{admin_designation_path(admin_designation)}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/designations/new.html.erb
<h1>New Designation</h1>
<br>
<%= render 'form' %>

app/views/admin/designations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_designation.name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @admin_designation.short_name %>
</p>

<p>
  <strong>Vacancy category:</strong>
  <%= @admin_designation.vacancy_category_id %>
</p>

<%= link_to 'Edit', edit_admin_designation_path(@admin_designation) %> |
<%= link_to 'Back', admin_designations_path %>