config/routes.rb
Pharmavacancy::Application.routes.draw do

  get "job_alert" => "job_alert#index"
  post "job_alert" => "job_alert#create"
  get "ajax/keywords"
  get "ajax/locations"
  get "ajax/candidates"

  get "job/:id/apply_to_job" => "job_handler#apply_to_job"
  get "job/:id/apply_job" => "job_handler#apply_job"
  get "job/:id/save_job" => "job_handler#save_job"
  get "download_resume" => "common#download_resume"

  resources :candidates, :only => [:show, :edit, :update] do 
    match '/profile' => 'candidates#profile'
    match '/profile/edit/:profile_name' => 'candidates#profile_edit'
    post '/candidate_update/:profile_name' => 'candidates#update_profile'
    delete '/candidate_destroy/:profile_name/:profile_id' => 'candidates#destroy_profile'
    get "/application_history" => "application_history#index"
    get "/application_history/show/:job_id" => "application_history#show"
    get "/saved_jobs" => "application_history#saved_jobs"
    get "/change_password" => "candidates#change_password"
    get "/job_alert" => "candidates#job_alert"
  end

  get 'candidate_registration/new' => 'candidate_registration#new'
  get 'candidate_registration/:id/step2' => 'candidate_registration#registration_step2'
  get 'candidate_registration/:id/step3' => 'candidate_registration#registration_step3'
  post 'candidate_session/perform_login' => 'candidate_login#perform_login'
  post 'candidate_registration/step1' => 'candidate_registration#create'
  put 'candidate_registration/:id/step2' => 'candidate_registration#step2_update'
  put 'candidate_registration/:id/step3' => 'candidate_registration#step3_update'

  get 'employer/login' => 'employer_dashboard#login'
  get 'employer/reset_password' => 'employer_dashboard#reset_password'
  post 'perform_login' => 'session#perform_login'
  get 'employer_dashboard' => 'employer_dashboard#index'
  get 'employer/:id/change_password' => 'employer_dashboard#change_password'
  get 'employer/:id/jobs' => 'employer_dashboard#change_password'
  get 'session/logout' => 'session#logout'
  post 'session/change_password' => 'session#change_password'
  get 'dashboard' => 'dashboard#index'
  get 'get_location_cities/:id' => 'common#location_cities'
  get 'session/forgot_password' => 'session#forgot_password'
  post 'session/send_password' => 'session#send_password'
  get 'activate/:code' => 'session#activate_user'

  resources :employers do 
    get "/applied_candidates" => "employer_dashboard#applied_candidates"
    get "/candidate_profile/:id" => "employer_dashboard#candidate_profile"
    get "/candidates" => "employer_dashboard#candidates"
    get "/candidate_search" => "employer_dashboard#candidate_search"
    post "/perform_search" => "employer_dashboard#perform_search"
    get "/upgrade_plans" => "employer_dashboard#upgrade_plans"
    get "/place_order/:plan_id" => "employer_dashboard#place_order"
    post "/create_order" => "employer_dashboard#create_order"
    get "/confirm_order/:order_id" => "employer_dashboard#confirm_order"
    resources :jobs
  end

  namespace :admin do
    resources :users
    resources :industries
    resources :employers, :only => [:index, :destroy]
    resources :jobs, :only => [:index, :destroy]
    get 'pending_jobs' => "jobs#pending_jobs"
    post "approve_job/:id" => "jobs#approve_job"
    get '/' => 'login#index'
    get 'login' => 'login#index'
    post 'perform_login' => 'login#perform_login'
    get 'logout' => 'login#logout'
    get 'dashboard' => 'dashboard#index'
    get 'reset_password' => 'login#reset_password'
    resources :cities
    resources :locations
    resources :job_types
    resources :pg_qualifications
    resources :ug_qualifications
    resources :designations
    resources :vacancy_categories
    resources :plans
    resources :candidates, :only => [:index, :destroy]
    post "set_featured_employer/:id" => "employers#set_featured_employer"
    post "suspend_user/:id" => "users#suspend_user"
    post "change_plan/:id/:plan_id" => "employers#change_plan"
  end

  get '/job_by/:section' => "dashboard#job_by_section"
  get '/job_by/:filter/:filter_id' => "dashboard#job_by_filter"
  post 'search' => "dashboard#search"
  get '/advanced_search' => "dashboard#advanced_search"
  post '/advanced_search' => "dashboard#perform_advanced_search"

  root :to => 'dashboard#index'

end

app/views/shared/_annual_salary_lakh.html.erb
<% selected = "" unless defined?(selected) %>
<option value="0"><%= label %></option>
<% (0..50).each do |element| %>
	<option value="<%= element %>" <% if selected == element %>selected<% end %>>
		<%= element %>
	</option>
<% end %>
<option value="50+">
	50+
</option>

app/views/shared/_application_home_jobs_employers.html.erb
<div class="cat-menu-section">
    <div class="left-cat-sec">
        <div id="menus" >     
            <ul class="menu">     
                <li><a href="#tabs-ind">Jobs By Category</a></li>
                <li><a href="#tabs-role">Jobs By Role</a></li>
                <li><a href="#tabs-loc"> Jobs By Location</a></li>
            </ul>
            <div id="tabs-ind" class="tab-container">
                <%= render :partial => "tab_content", :locals => { :items => top_categories, :more_url => job_by_section_path('category') } %>
            </div>
            <div id="tabs-role" class="tab-container">
                <%= render :partial => "tab_content", :locals => { :items => top_designations, :more_url => job_by_section_path('designation') } %>
            </div>
            <div id="tabs-loc" class="tab-container">
                <%= render :partial => "tab_content", :locals => { :items => top_locations, :more_url => job_by_section_path('location') } %>
            </div>
            <div class="clr"></div>
        </div>
        <div class="clr"></div>
        <div class="recent-job-sec">
            <%= render "/shared/hot_jobs" %>
        </div>
        <div class="clr"></div>
        <div class="company-add-sec">
            <div class="hot-employer">
                <%= render "/shared/hot_employers" %>
            </div>
        </div>
    </div>
    <div class="right-cat-sec">
        <%= render "/shared/featured_employers" %>
    </div>
</div>

app/views/shared/_application_loginpopup.html.erb
<div class="overlay_popup" id="overlay_popup" style="display:none;"></div>
<!-- newsletter data start-->
<div id="loginformwindow"  class="informationwindow">
    <div class="lHead" >
        <a href="javascript:void(0);" class="boxclose" id="boxclose" onclick="closeCandidateLoginPopup();">x</a>
        <h1 class="lhs" style="font-size:18px; font-weight:bold;">Login</h1>
    </div>
    <div style="padding-top:10px;">
        <div class="response_error js-response_error hide"></div>
        <form action="#" method="post" accept-charset="utf-8" id="everywherejslogfrm" name="everywherejslogfrm candidate_login_form">
            <input name="user[role]" id="everywherejobid" type="hidden" value="Candidate" />
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div style="width:350px !important; margin:0px auto;" >
                <table class="tbl candidate_login_table">
                    <tr>
                        <td width="25%">Email-ID</td>
                        <td width="75%">
                            <input name="user[user_name]" id="everywhereusername" type="text" title="User Name"  class="rightforminput js-user_name" style="width:228px !important; height:25px !important;" autocomplete="off"/>
                            <span class="error_msg hide js-error_msg">
                                Please enter valid email id.
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td  style="vertical-align:middle;">Password</td>
                        <td>
                            <input name="user[password]" id="everywherepass" type="password" style="margin-top:10px;width:228px !important; height:25px !important;"  title="Password"   class="rightforminput js-password" />
                            <span class="error_msg hide js-error_msg">
                                Please enter password.
                            </span>
                        </td>
                    </tr>   
                </table>
                <div class="span-lg">
                    <button type="button" id="sumbit-login-form" class="btn btn-primary" >Login</button>
                </div>
                <div style="margin-left:65px;display:none;" id="wait_div">
                    <table>
                        <tr>
                            <td>
                                <img src="<%= image_path('loading-circle.gif') %>" width="30" />
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="span-lg" id="register_forgot_id">
                    <span style="margin-right:90px;">
                        <a  href="<%= candidate_registration_new_path %>" class="getStartedClass_extra">Register Now</a>
                    </span>
                    <!-- <span>
                        <a href="#" style="font-weight:normal;">Forgot Password?  </a>
                    </span> -->
                    <div class="clear"></div>
                </div>
            </div>
            </form>
        </div>
</div>

app/views/shared/_application_search.html.erb
<div id="search-section">
    <div class="search-section">
        <div id="left-search-sec">
        <% if flash[:notice].present? %>
            <span style="color: #3c763d; font-size: 12px;">
                <%= flash[:notice] %>
            </span>
        <% end %>
        <form action="<%= search_path %>" accept-charset="utf-8" method="post" class="js-search_form"> 
             <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
            <h2><img src="<%= image_path('search.png') %>"  width="15" height="15" alt="" /><span>Find</span> Jobs In India</h2>
            <p>Thousands of latest job Opening in India every day</p>           
            <div class="search-one">
                <ul>
                    <li>
                        <input type="text" id="keywords" class="search_form_field js-search_keywords" placeholder="Type Your Skills, Designation etc." value="" name="search[keywords]" />
                    </li>
                    <li>
                        <input type="text" id="search_location" class="search_form_field js-search_location" placeholder="Type City Where You Want To Work" value="" name="search[location]" />
                    </li>
                    <li>
                        <select id="experience" name="search[experience]">
                            <%= render :partial => 'shared/sal_exp_dropmenu_options', :locals => { :label => 'Experience', :selected_id => ""}  %>
                        </select>
                    </li>
                </ul>
            </div>
            <div class="clr"></div>
            <div class="search-two">
                <ul>
                    <li>
                        <select id="min_salary" name="min_salary">
                            <%= render :partial => 'shared/sal_exp_dropmenu_options', :locals => { :label => 'Salary', :selected_id => ""}  %>
                            </select>
                        <br />
                        <span>Salary in Lakhs per Annum </span>
                    </li>
                    <li>
                        <a href="#">
                            <div class="search_button js-search">Search</div>
                        </a>
                    </li>
                </ul>
                <div class="search_error hide js-search_error">
                    Please enter Keywords or Location or select Job Category to search.
                </div>
            </div>
            </form>
            <div class="clr"></div>
        </div>
        <!--left-search sec end-->
        <div id="right-search-sec" 
                style="width:385px;"
                >
            <div class="col" style="width:100%;">
                <div class="cta-backer">
                    <div class="cols-wrapper cols-2">
                        <div class="col">
                            <div class="cta-text">
                                <p>Accelerate your job search now!</p>
                            </div>
                        </div>
                        <div class="col nomargin">
                            <div class="cta-buttons">
                                <a href="<%= candidate_registration_new_path %>">
                                    <div class="orangecta noselect getStartedClass1">
                                        Get Started
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <!--class search section end-->
</div>
<!--search sec end-->

app/views/shared/_application_top_employers.html.erb
<div id="top-employer">
    <h3>Top Employers</h3>
    <ul class="top-emp-list">
        <% get_top_employers.each do |employer| %>
            <li>
                <a href="<%= section_url(employer) %>">
                    <img src="<%= employer_logo_url(employer) %>" alt="<%= employer.company_name%>" title="<%= employer.company_name%>" width="110" height="60" />
                </a>
            </li>
        <% end %>
    </ul>
</div>

app/views/shared/_candidate_nav_on.html.erb
<div class="clr"></div>
<div class="nav" style="margin-right: 70px;">
    <ul id="nav-li">
        <li class="active">
            <a href="<%= root_path %>">Home</a>
        </li>
        <li class="main-line" data-value="search-overwrite-first">
            <a href="#" class="search-drop" data-value="search-overwrite-first">
                Search jobs
            </a>
            <div class="search-drop-down search-overwrite-first" style="width: 100%;">
                <ol>
                   <li><a href="/advanced_search" class="simpleWColor"> Advance Search </a></li>
                    <li><a href="/job_by/employer" class="simpleWColor"> Jobs By Company </a> </li>
                    <li><a href="/job_by/category" class="simpleWColor"> Jobs By Functional Area </a> </li>
                    <li><a href="/job_by/location" class="simpleWColor"> Jobs By Location </a> </li>
                    <li><a href="/job_by/designation" class="simpleWColor"> Jobs By Role </a> </li>
                </ol>
            </div>
        </li>
    </ul>
</div>

app/views/shared/_change_password.html.erb
<div class="login_div">
    <% if flash[:error].present? %>
        <%= render :partial => "/shared/alert_message", :locals => { :message => flash[:error] } %>
    <% end %>
    <form class="chnage_password_form js-change_password_form" action="<%= session_change_password_path %>" method="post">
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 
        <div class="form-group js_old_password_group">
            <label for="old_password" class="col-sm-2 control-label label "><span class="required">*</span>Old Password:</label>
            <input type="password" name="user[old_password]" class="form-control change_pass_input js-old_password" id="old_password"/ >
            <p class="error_message error-position js-error hide">
                Please enter valid old password.
            </p>
            
        </div>
        <div class="form-group js-password_group">
            <label for="password" class="col-sm-2 control-label label "><span class="required">*</span>New Password:</label>
            <input type="password" name="user[password]" class="form-control change_pass_input js-new_password" id="password"/ >
            <p class="error_message error-position js-error hide">
                Please enter valid new password.
            </p>
        </div>
        <div class="form-group js-confirm_password_group">
            <label for="old_password" class="col-sm-2 control-label label "><span class="required">*</span>Confirm New Password:</label>
            <input type="password" name="user[confirm_password]" class="form-control change_pass_input js-confirm_new_password" id="old_password"/ >
            <p class="error_message error-position js-error hide">
                Please enter valid new confirm password.
            </p>
            <p class="error_message error-position js-confirm_password_error_match hide">
                Password and confirm Password should be same.
            </p>
        </div>
        <div>
            <button type="button" id="sub" class="btn btn-primary js-change_password_submit">Submit</button>
            <a href="<%= cancel_path %>">
                <button type="button" class="btn btn-primary employer_login_submit">Cancel</button>
            </a>
        </div>
    </form>
</div>

app/views/shared/_days.html.erb
<option value="0"><%= label %></option>
<% (1..31).each do |element| %>
	<option value="<%= element %>">
		<%= element %>
	</option>
<% end %>

app/views/shared/_employer_nav_on.html.erb
<div class="clr"></div>
<div class="nav">
  <ul id="nav-li">
        <li class="active">
            <a href="<%= employer_dashboard_path %>">Home</a>
        </li>
        <li class="main-line" data-value="search-overwrite-first">
            <a href="<%= employer_jobs_path(@employer) %>" class="search-drop">Posted Jobs</a>
        </li>
        <li class="main-line" data-value="search-overwrite-first">
            <a href="<%= employer_applied_candidates_path(@employer) %>" class="search-drop">Applied Candidates</a>
        </li>
        <li class="main-line" data-value="search-overwrite-first">
            <a href="<%= employer_candidates_path(@employer) %>" class="search-drop">All Candidates</a>
        </li>
        <li class="main-line" data-value="search-overwrite-first">
            <a href="<%= employer_upgrade_plans_path(@employer) %>" class="search-drop">My Plan</a>
        </li>
        <li class="main-line" data-value="search-overwrite-second">
            <a href="<%= edit_employer_path(@employer) %>">My Account</a>
        </li>
        <li class="main-line" data-value="search-overwrite-first">
            <a href='<%=  "/employer/#{@employer.id}/change_password" %>' class="search-drop">Change Password</a>
        </li>
    </ul>
</div>

app/views/shared/_featured_employers.html.erb
<div class="future-employer">
    <div class="f-heading">
        <img src="<%= image_path('feature-icon.jpg')%>" width="23" height="24" alt="" />
        <h3>Featured Employers</h3>
        <ul class="feature-list">
            <% get_featured_employers.each do |employer| %>
                <li>
                    <div>
                        <div class="empl-logo">
                            <img src="<%= employer_logo_url(employer) %>" width="78" height="60" alt="" />
                        </div>
                        <div class="emp-details">
                            <a href="<%= section_url(employer) %>" >    
                                <span><%= employer.company_name %></span>
                            </a>
                            <h4 class="simpleBColor">
                                <%= truncate_description(employer.about_company) %>
                            </h4>
                            <h4 class="simpleBColor">
                                <%= employer.city.present? ? employer.city.name : "" %>
                            </h4>
                        </div>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_hot_jobs.html.erb
<h3>Recent Hot Jobs</h3>
<div class="multi_column col_count_two" column-count="2">
    <% get_hot_jobs.each do |job| %>
        <a title="<%= job.title %>" target="_blank" href="<%= apply_to_job_path(job) %>">
            <%= job.title %>
        </a>
        <h4>Jobs in <%= job.location_id %></h4>
            <h4><%= show_exp_range(job) %> - <%= job.designation.name %></h4>
    <% end %>
</div>
<div class="clr"></div>

app/views/shared/_main_menu.html.erb
<p class="log-sec">
    <span>
        <a href="<%= employer_login_path %>" id="loginshowid">Login</a>
    </span> 
    to post jobs for you!  &nbsp;|&nbsp; New Employer
    <span>
        <a href="<%= new_employer_path %>">Sign Up</a>
    </span>
</p>
<div class="clr"></div>
<h2>
    <img src="<%= image_path('email-icon.png') %>" width="25" height="18" alt="Support Mail" />
    <a class="support_email_text" href="mailto:support@pharnavacancies.com">support@pharnavacancies.com</a>
</h2>
<div class="clr"></div>
<div class="nav">
  <ul id="nav-li">
                        <li class="active">
                            <a href="<%= employer_dashboard_path %>">Home</a>
                        </li>
                        <li><a href="<%= new_employer_path %>">New Employer</a></li>
                        
                        <li><a href="<%= employers_path%>">Employer Zone</a></li>
                    </ul>
</div>

app/views/shared/_pagination.html.erb
<!-- pagination div starts here-->
<div style="float: right;">
   <%= will_paginate objects, renderer: BootstrapPagination::Rails %>
</div>

app/views/shared/_search_zero.html.erb
<div class="zero_result">
    <div class="large_text">We could not find jobs matching your search criteria.</div> 

    <div class="small_text"> Did you enter wrong spelling of any word? <br> Only cities/states/country names are accepted in location field <br> You can browse jobs by 
    </div>
</div>